name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Check HTML syntax
        run: |
          sudo apt update
          sudo apt install tidy -y
          tidy -e index.html || true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SECRET_KEY_1 }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY_2 }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://kollejproject --delete
